name: Continuous Integration Pipeline
run-name: CI Pipeline triggered by ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - run: echo "Job Information"
      - run: echo "Repo:    ${{ github.repository }}"
      - run: echo "Branch:  ${{ github.ref }}"
      - run: echo "OS:      ${{ runner.os }} on GitHub"
      - run: echo "Event:   ${{ github.event_name }}"
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential
