name: Continuous Integration Pipeline
run-name: CI Pipeline triggered by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Job Info
        run: |
          echo "Branch:  ${{ github.ref }}"
          echo "OS:      ${{ runner.os }} on GitHub"
          echo "Event:   ${{ github.event_name }}"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential
          CMAKE_VERSION=3.27.7
          wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-aarch64.sh
          chmod +x cmake-${CMAKE_VERSION}-linux-aarch64.sh
          sudo ./cmake-${CMAKE_VERSION}-linux-aarch64.sh --skip-license --prefix=/usr/local

      - name: Verify CMake Installation
        run: cmake --version

      - name: Build Project
        run: |
          mkdir -p build
          cd build 
          cmake ..
          cmake --build .

      - name: Run Microbenchmarks
        run: |
          cd ./build/bin/
          ./throughput_microbenchmark
          ./latency_microbenchmark
          ./neon_microbenchmark

      - name: Run copy_driver
        run: |
          cd ./build/bin/
          ./copy_driver

      - name: Run matmul_driver
        run: |
          cd ./build/bin/
          ./matmul_driver

      - name: Run Unittests
        run: |
          cd ./build/
          ctest --verbose
