name: Continuous Integration Pipeline
run-name: CI Pipeline triggered by ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Job Info
        run: |
          echo "Branch:  ${{ github.ref }}"
          echo "OS:      ${{ runner.os }} on GitHub"
          echo "Event:   ${{ github.event_name }}"
      
      - name: Install dependencies
        run: |
          brew update
          brew install gcc make
